/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public class App {
    public static void main(String[] args) {
        Person person1 = new Person("Jonny", 34);
        System.out.println(person1);
        person1.setAge(24);
        System.out.println(person1);
    }
}
